<?php

/**
 * @file
 * dmonitor module main code.
 * 
 */

/**
 * Implements hook_menu().
 */
function dmonitor_menu() {
  
  return array(
    
    // List modules.
    'admin/dmonitor/list/%' => array(
      'page callback' => 'dmonitor_json_list',
      'page arguments' => array(3),
      'file' => 'dmonitor.callbacks.inc',
      'access callback' => TRUE, //'dmonitor_custom_access',
    ),
    
    // Check if module installed.
    'dmonitor/check-installed/%' => array(
      'page callback' => 'dmonitor_check_installed',
      'page arguments' => array(2),
      'file' => 'dmonitor.callbacks.inc',
      'access callback' => TRUE,      
    ),
    
    // Admin settings.
    'admin/config/system/dmonitor' => array(
      'title' => 'D-Monitor',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('dmonitor_settings_form'),
      'file' => 'dmonitor.admin.inc',
      'access callback' => TRUE,      
    )
  );  
}